### ISSUE TITLE
chore: Problema con el formato de código al trabajar en componentes (por ejemplo, Sponsors.astro)

### ISSUE THREAD

**Issue by geekhadev** [midudev/jsconf.es#19]
Al contribuir al proyecto, noté que el formato del código cambia al actualizar mi `fork`. Esto genera inconsistencias en el estilo del código, lo cual puede dificultar la colaboración y revisión de `PR`.

Algunos ejemplos del formateo:

Antes:
```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M16.0037 9.41421L7.39712 18.0208L5.98291 16.6066L14.5895 8H7.00373V6H18.0037V17H16.0037V9.41421Z" fill="currentColor"></path>
</svg>
```

Después:
```
<svg
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M16.0037 9.41421L7.39712 18.0208L5.98291 16.6066L14.5895 8H7.00373V6H18.0037V17H16.0037V9.41421Z"
      fill="currentColor"
    ></path>
</svg>
```

Antes:
```
<div class="flex items-start justify-between gap-12 mb-12 flex-col md:flex-row">
```

Después:
```
<div
    class="flex items-start justify-between gap-12 mb-12 flex-col md:flex-row"
>
```

Impacto:
- podría estar generando `commits` innecesarios en caso de que cada quien tenga un formato diferente.

Propuesta:
Sugiero instalar un formateador de código e incluir la configuración y la forma de ejecución al proyecto para evitar pasar nuestro estilo de código por sobre el equipo. En primera instancia preferiría que el equipo organizador elija una configuración y nosotros nos adaptamos.

**Comment by midudev** [comment]
He añadido eslint y prettier para formatear el código automáticamente.
